title: Web of Tomorrow
organizationName: Web of Tomorrow
podcastSubtitle:
managerName: Adam Harris
managerEmail: aharris88@gmail.com
squareLogo: assets/uploads/logo2.png
description: "A podcast about JavaScript, web development, web design, and technology."
baseurl: ""
url: "http://www.weboftomorrowpodcast.com"

# Google analytics
google_analytics: UA-31980509-13

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: /:title
paginate:     3
sass:
  compressed: true
